collection_name: agent
persist_directory: chroma_db
k: 2
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: ["txt","pdf","json"]

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n","\n",".","!","?","。","！","？",""]